[package]
name = "code-analyzer"
version = "0.1.0"
edition = "2024"
authors = ["Jithin Aji <jithin@example.com>"]
description = "A lightweight terminal application to analyze and compare source files"
license = "MIT"

[package.metadata.deb]
maintainer = "Jithin Aji <jithin@example.com>"
assets = [
    ["target/release/code-analyzer", "usr/bin/code-analyzer", "755"],
]

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ratatui = "0.26"
crossterm = "0.27"
oxc_parser = "0.143.0"
oxc_allocator = "0.143.0"
oxc_ast = "0.143.0"
oxc_span = "0.143.0"
